# Generated by Django 5.1.6 on 2025-02-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_address_profile_city_profile_mpesa_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="mpesa_number",
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(default="0700000000", max_length=15, unique=True),
        ),
    ]
