# Generated by Django 5.1.6 on 2025-04-09 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_profile_mpesa_number_profile_phone_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
