# Generated by Django 5.1.6 on 2025-04-08 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("menu", "0002_alter_category_options_alter_menuitem_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ["-added_at"],
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
            },
        ),
        migrations.AlterField(
            model_name="cart",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the item was first added or the entry was created.",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="item",
            field=models.ForeignKey(
                help_text="The menu item added to the cart.",
                on_delete=django.db.models.deletion.CASCADE,
                to="menu.menuitem",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of this specific item in the cart."
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                help_text="The user who owns this cart item.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
