# Generated by Django 5.1.6 on 2025-04-08 09:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["name"],
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of the name. Leave blank to auto-generate.",
                max_length=110,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when the item was created.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_available",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Is this item currently available for ordering?",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the item was last updated."
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description for the category.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Name of the category.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                help_text="The category this menu item belongs to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="menu_items",
                to="menu.category",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(help_text="Detailed description of the menu item."),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="gluten_free",
            field=models.BooleanField(
                default=False, help_text="Is this item gluten-free?"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image for the menu item.",
                null=True,
                upload_to="menu_items/",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="name",
            field=models.CharField(
                db_index=True, help_text="Name of the menu item.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price of the menu item in KES.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="vegetarian",
            field=models.BooleanField(
                default=False, help_text="Is this item vegetarian?"
            ),
        ),
    ]
