# Generated by Django 5.1.6 on 2025-09-12 10:12

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_brand_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="dietary_info",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="dimensions",
            field=models.CharField(
                blank=True,
                help_text="e.g., 'W: 85in, H: 30in, D: 34in'",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="material",
            field=models.CharField(
                blank=True,
                help_text="e.g., 'Velvet Fabric, Solid Wood'",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="e.g., 'Sofa Sets', 'Dining Tables'",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Select parent for sub-categories. e.g., '3-Seater' under 'Sofa Sets'.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="menu.category",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(
                help_text="Detailed description, dimensions, and materials."
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="name",
            field=models.CharField(
                db_index=True, help_text="e.g., 'Modern Velvet Sofa'", max_length=255
            ),
        ),
    ]
