# Generated by Django 5.1.6 on 2025-04-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the branch (e.g., Kings Choice - Ngong, Uptown Mall).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier. Leave blank to auto-generate.",
                        max_length=110,
                        unique=True,
                    ),
                ),
                (
                    "address_line",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Kawangware, Ngong Town, Kitengela",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("city", models.CharField(default="Nairobi", max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Branch specific contact number, if any.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "simphony_loc_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Simphony Location Reference ID for this branch.",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "simphony_rvc_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Simphony Revenue Center Reference ID for this branch.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_active_online",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Check if this branch can currently accept and fulfill online orders.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Location",
                "verbose_name_plural": "Store Locations",
                "ordering": ["name"],
            },
        ),
    ]
