name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # Change if your production branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}  # Ensure Fly.io API token is available

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL="$HOME/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          echo "$FLYCTL_INSTALL/bin" >> $GITHUB_PATH

      - name: Authenticate with Fly.io
        run: flyctl auth login || echo "Using FLY_API_TOKEN..."
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        run: flyctl deploy -a samakisamaki --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
